# -*- coding: utf-8 -*-
"""Light.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iuuFTs4bUe2c8UxUq08ImnIdEllYm6QD

Filtra os conjunto somente da Distribuidora Light que tem área de concessão em parte do Rio de Janeiro (considerando 2023) para o teste da inferencia do modelo
"""

import csv
import pandas as pd
import os
import json

pd.set_option('display.max_columns', None)

# Conecta o serviço com o Drive
from google.colab import drive
drive.mount('/content/drive')

# Raiz
! ls '/content/drive/MyDrive/Mestrado/Ordens_servico/'

"""# Preprocess"""

year = 2022

interrupcoes = pd.read_csv("/content/drive/MyDrive/Mestrado/Ordens_servico/Ordens_servico/test_interrupcoes_collect_ckan_{}.csv".format(year))

interrupcoes = interrupcoes[interrupcoes.NomAgenteRegulado.str.contains('LIGHT')]

interrupcoes

interrupcoes_array = interrupcoes.DscConjuntoUnidadeConsumidora.values

interrupcoes_dict = {}
interrupcoes_dict["conjuntos"] = list(interrupcoes_array)
interrupcoes_dict

with open("/content/drive/MyDrive/Mestrado/Ordens_servico/Ordens_servico/CONJUNTOS_LIGHT.json", 'w') as f:
  json.dump(interrupcoes_dict, f)

